version = 0.1
[default.deploy.parameters]
stack_name = "WPLaunchConfigStack"
resolve_s3 = true
s3_prefix = "WPLaunchConfigStack"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "LatestAL2AmiId=\"/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2\" DatabaseName=\"WPDatabase\" DatabaseHostName=\"mydbcluster.cluster-c1k40gysuazl.us-east-1.rds.amazonaws.com\" DatabaseUsername=\"admin\" Username=\"wpadmin\" Email=\"carlosdf@hotmail.com\" EC2ServerInstanceType=\"t3.medium\" ALBDnsName=\"myWPAppALB-780364146.us-east-1.elb.amazonaws.com\" WPElasticFileSystemID=\"fs-063fd67f8d1ec4182\""
image_repositories = []
