version = 0.1
[default.deploy.parameters]
stack_name = "WPCloudFrontStack"
resolve_s3 = true
s3_prefix = "WPCloudFrontStack"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "CloudFrontAcmCertificate=\"\" WPDomainName=\"\" ALBDnsName=\"myWPAppALB-780364146.us-east-1.elb.amazonaws.com\""
image_repositories = []
